Task 01 started
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #1
Opened 2020-11-03 16:48 UTC by ivanzuev78

Изменил логику функции, добавил проверку, что ноль не является степенью двойки. 
С тестами возникла проблема: при запуске выдает ошибку импорта функции, причём в самом файле теста не ругается и если его запустить как обычный файл, он на импорт не ругается. Пытался прописывать как абсолютный путь, так и относительный. 
Так же добавил в тест проверку на ноль.

2020-11-03 18:41 UTC, Cjkjvfnby requested changes
Please add the task definition to the file or PR description.

2020-11-03 18:41 UTC, Cjkjvfnby commented on HomeWork1/Tasks/sample_project/tests/test_calculator.py
> +
option 1
- check the path where import search starts `print(sys.path)`
- add path with your module to imports  `sys.path.append('....')`

oprtion 2:
move test to the same folder as file

2020-11-07 18:06 UTC, ivanzuev78 commented on HomeWork1/Tasks/sample_project/tests/test_calculator.py
> +
Thanks. I mooved it to the same folder as file and it works.

2020-11-07 23:00 UTC, Cjkjvfnby approved these changes

2020-11-08 06:38 UTC, merged