Hw 2 task 5
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #10
Opened 2020-11-07 17:28 UTC by ivanzuev78

Homework 2 task 5 done

2020-11-08 13:07 UTC, Cjkjvfnby requested changes

2020-11-08 13:07 UTC, Cjkjvfnby commented on HomeWork_2/hw5.py
> +def custom_range(*args) -> List[str]:
At least first argument is alway a sequence, so lets add it here.

2020-11-08 13:07 UTC, Cjkjvfnby commented on HomeWork_2/hw5.py
> +    if isinstance(args[-1], int):
What is this check about?

2020-11-08 13:07 UTC, Cjkjvfnby commented on HomeWork_2/test_hw5.py
> +def test_custom_range_example_1():
`any iterable of unique values` what does it means for you?

2020-11-08 13:44 UTC, ivanzuev78 commented on HomeWork_2/hw5.py
> +    if isinstance(args[-1], int):
When the last argument is int, we use it as a step. So, I cheсk it.

2020-11-08 13:55 UTC, ivanzuev78 commented on HomeWork_2/test_hw5.py
> +def test_custom_range_example_1():
It means, that we have an object with the method __iter__, that returns inner objects, and all inner objects are unique.

2020-11-08 13:59 UTC, ivanzuev78 commented on HomeWork_2/hw5.py
> +def custom_range(*args) -> List[str]:
How we can do it? When we write "(*args: Sequence)" it means, that all args are Sequences, but the last one can be integer.
![custom_range](https://user-images.githubusercontent.com/63249816/98466951-c3ba6e80-21e3-11eb-95df-a046bf02aa39.PNG)

2020-11-08 20:58 UTC, Cjkjvfnby commented on HomeWork_2/test_hw5.py
> +def test_custom_range_example_1():
You havenot mention about objects type.  Are inner objects can be only strings or they can have any type? For example int?

2020-11-08 21:00 UTC, Cjkjvfnby commented on HomeWork_2/hw5.py
> +def custom_range(*args) -> List[str]:
Positional arguments:  `def custom_range(sequence: Sequence, *args)`

2020-11-08 21:01 UTC, Cjkjvfnby commented on HomeWork_2/hw5.py
> +def custom_range(*args) -> List[str]:
`List[str]`  why?

2020-11-08 21:02 UTC, Cjkjvfnby commented on HomeWork_2/hw5.py
> +    if isinstance(args[-1], int):
Can we check if step is specified in a diffeent way?

2020-11-08 21:17 UTC, Cjkjvfnby requested changes
Please see comment

2020-11-11 21:59 UTC, ivanzuev78 commented on HomeWork_2/hw5.py
> +def custom_range(*args) -> List[str]:
Because I didn't think about other types.

2020-11-11 22:01 UTC, ivanzuev78 commented on HomeWork_2/hw5.py
> +    if isinstance(args[-1], int):
Yes.

2020-11-11 22:02 UTC, ivanzuev78 commented on HomeWork_2/test_hw5.py
> +def test_custom_range_example_1():
Yes, I didn't think about types. This changes all.

2020-11-11 22:33 UTC, Cjkjvfnby approved these changes

2020-11-11 22:33 UTC, Cjkjvfnby commented on HomeWork_2/hw5.py
> +    if len(args) == 0:
I think args should be at least size 1.  (stop | stop:start | stop:start:step )

2020-11-11 22:33 UTC, Cjkjvfnby commented on HomeWork_2/hw5.py
> +    return [i for i in sequence[first_elem:last_elem:step]]
```
return sequence[first_elem:last_elem:step]
```

2020-11-11 22:47 UTC, merged