Homework 3 task 2 done
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #15
Opened 2020-11-08 13:09 UTC by ivanzuev78

Homework 3 task 2 done

2020-11-11 19:19 UTC, Cjkjvfnby requested changes

2020-11-11 19:19 UTC, Cjkjvfnby commented on HomeWork_3/task02/test_task_2.py
> +    fast_calculate([i for i in range(501)])
What will be the length of the range(501)?

2020-11-11 19:19 UTC, Cjkjvfnby commented on HomeWork_3/task02/test_task_2.py
> +def test_calculate_equal_result():
Please live this test and remove others.  Unittests are about correctness, not about time measuring.

2020-11-11 19:19 UTC, Cjkjvfnby commented on HomeWork_3/task02/task02.py
> +def fast_calculate(values: List[int]) -> int:
What the max number of tasks you can start on your machine?

2020-11-11 20:29 UTC, ivanzuev78 commented on HomeWork_3/task02/task02.py
> +def fast_calculate(values: List[int]) -> int:
To tell the truth, I don't know.

2020-11-11 20:33 UTC, ivanzuev78 commented on HomeWork_3/task02/test_task_2.py
> +def test_calculate_equal_result():
Ok. 
But what about "Calculation time should not take more than a minute." in the task?
Or using "threading" is enough?

2020-11-11 20:35 UTC, ivanzuev78 commented on HomeWork_3/task02/task02.py
> +def fast_calculate(values: List[int]) -> int:
I suppose it connected with the number of cores or with "stack overflow" error.

2020-11-11 20:37 UTC, ivanzuev78 commented on HomeWork_3/task02/test_task_2.py
> +    fast_calculate([i for i in range(501)])
len(range(501)) == 1
I thought than number=500 must be included.
Changed.

2020-11-11 20:57 UTC, Cjkjvfnby commented on HomeWork_3/task02/test_task_2.py
> +def test_calculate_equal_result():
It is not a functional requirement.    As I undetstant it is a tip for implementation: if it is too long it may be an issue.

2020-11-11 21:02 UTC, Cjkjvfnby commented on HomeWork_3/task02/task02.py
> +def fast_calculate(values: List[int]) -> int:
Get more sleep  `time.sleep(random.randint(10, 20))`   and may be add more threads.  

Since the task is fast and starting a new thread may be slow, you can have less than 500 threads simultaneously.

2020-11-11 21:04 UTC, Cjkjvfnby requested changes
Try to reproduce an error becasue of too many tasks.

2020-11-12 10:12 UTC, ivanzuev78 commented on HomeWork_3/task02/test_task_2.py
> +def test_calculate_equal_result():
Understand.

2020-11-12 13:40 UTC, ivanzuev78 commented on HomeWork_3/task02/task02.py
> +def fast_calculate(values: List[int]) -> int:
I'll do. 
I had made numb of threads customizable.

2020-11-12 16:03 UTC, ivanzuev78 commented
My computer can count 10^5 values in 10^5 threads, and it takes 29 sec. Github can't create 10^4 threads in the test.

2020-11-12 16:11 UTC, ivanzuev78 commented
Wow. At the third time, Github creates 10^4 threads. First two checks were failed.

2020-11-12 16:28 UTC, ivanzuev78 commented on HomeWork_3/task02/test_task_2.py
> +    assert True
I know, that I shouldn't code in such way. That is only for an experiment. I'll delete this after review.

2020-11-12 17:22 UTC, Cjkjvfnby commented
Please don't do any heavy computation in github actions.

2020-11-12 17:23 UTC, Cjkjvfnby approved these changes
Please remove long tests.

2020-11-12 17:24 UTC, merged