Homework 3 task 3 done
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #19
Opened 2020-11-11 18:43 UTC by ivanzuev78

2020-11-11 19:43 UTC, Cjkjvfnby requested changes

2020-11-11 19:43 UTC, Cjkjvfnby commented on HomeWork_3/task03/task03.py
> +    def apply(self, data: List[dict]) -> List[dict]:
Why `List[dict]`?

2020-11-11 19:43 UTC, Cjkjvfnby commented on HomeWork_3/task03/task03.py
> +            if (
replace if to return

2020-11-11 19:43 UTC, Cjkjvfnby commented on HomeWork_3/task03/task03.py
> +    for key in keywords:
what type of the `key`?  Does this name good for it?

2020-11-11 19:43 UTC, Cjkjvfnby commented on HomeWork_3/task03/test_task_3.py
> +    ).apply(range(-10, 10)) == [2, 4, 6, 8]
`range(-10, 10)`  just hardcode some numbers here.

2020-11-11 19:43 UTC, Cjkjvfnby commented on HomeWork_3/task03/test_task_3.py
> +    sample_data = [
Move sample to fixture.

Create two separate tests.

2020-11-11 19:55 UTC, ivanzuev78 commented on HomeWork_3/task03/task03.py
> +    def apply(self, data: List[dict]) -> List[dict]:
Because I thought about example, not about function. 
Fixed.

2020-11-11 19:59 UTC, ivanzuev78 commented on HomeWork_3/task03/task03.py
> +            if (
Done

2020-11-11 20:00 UTC, ivanzuev78 commented on HomeWork_3/task03/task03.py
> +    for key in keywords:
type(key) is str
Renamed

2020-11-11 20:15 UTC, ivanzuev78 commented on HomeWork_3/task03/test_task_3.py
> +    sample_data = [
Done

2020-11-11 20:15 UTC, ivanzuev78 commented on HomeWork_3/task03/test_task_3.py
> +    ).apply(range(-10, 10)) == [2, 4, 6, 8]
Ok

2020-11-13 17:32 UTC, Cjkjvfnby requested changes

2020-11-13 17:32 UTC, Cjkjvfnby commented on HomeWork_3/task03/task03.py
> +    def __init__(self, *functions: Callable):
When you change signature of the method, don't forget to check if docstring is still actual.

2020-11-13 17:32 UTC, Cjkjvfnby commented on HomeWork_3/task03/task03.py
> +    for keyword in keywords:
Can you use list comprehension here?

2020-11-13 17:32 UTC, Cjkjvfnby commented on HomeWork_3/task03/test_task_3.py
> +    yield input
Why do you need yield here?

2020-11-13 17:32 UTC, Cjkjvfnby commented on HomeWork_3/task03/test_task_3.py
> +def specified_filter_input():
Could you rename sample_data and specified_filter_input so I can understand the difference between them?

2020-11-13 17:32 UTC, Cjkjvfnby commented on HomeWork_3/task03/test_task_3.py
> +def test_specified_filter__no_one_in_input_are_good(specified_filter_input):
`__` -> `_`

2020-11-13 18:29 UTC, ivanzuev78 commented on HomeWork_3/task03/task03.py
> +    def __init__(self, *functions: Callable):
I will try to remember.

2020-11-13 18:40 UTC, ivanzuev78 commented on HomeWork_3/task03/test_task_3.py
> +def test_specified_filter__no_one_in_input_are_good(specified_filter_input):
Done

2020-11-13 18:41 UTC, ivanzuev78 commented on HomeWork_3/task03/test_task_3.py
> +def specified_filter_input():
Yes, of course.

2020-11-13 19:06 UTC, Cjkjvfnby requested changes

2020-11-13 19:06 UTC, Cjkjvfnby commented on HomeWork_3/task03/test_task_3.py
> +def test_specified_filter_no_one_in_input_are_good(some_data_to_test_filter):
`some_data_to_test_filter`  `data_from_example_of_the_task`   both names are abstract and both of them does not describe the content.    If next person decides to add one more test which of the should be used?

Maybe you dont need a fixtures?  Just put samples to each test.   You don't need good name inside the test, and each test can use own set of data.   Actually it is not a duplication, becasue if you change data inside one test, you don't need to change another.

2020-11-13 19:27 UTC, ivanzuev78 commented on HomeWork_3/task03/task03.py
> +    Helper filter class. Accepts single-argument
Not single-argument, but single-argument functions.

2020-11-13 19:34 UTC, ivanzuev78 commented on HomeWork_3/task03/test_task_3.py
> +def test_specified_filter_no_one_in_input_are_good(some_data_to_test_filter):
Very useful note.

2020-11-14 09:57 UTC, Cjkjvfnby requested changes

2020-11-14 14:11 UTC, ivanzuev78 commented on HomeWork_3/task03/test_task_3.py
> +def test_specified_filter_all_in_input_are_good():
Test added

2020-11-14 14:33 UTC, Cjkjvfnby approved these changes

2020-11-14 15:01 UTC, merged