Task 02 done
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #2
Opened 2020-11-03 16:50 UTC by ivanzuev78

Задание выполнено, тест написан, вопросов нет.

2020-11-03 18:57 UTC, Cjkjvfnby requested changes

2020-11-03 18:57 UTC, Cjkjvfnby commented on HomeWork1/Tasks/task02.py
> +def check_fibonacci(data: Sequence) -> bool:
![image](https://user-images.githubusercontent.com/171597/98028029-8ee29c00-1e1e-11eb-9f12-fc3fcbadf6c0.png)

It is good practice to do a self-review before submitting PR.   It usually helps to find small details.  
In that case signature was chnaged. Is it better when it was before?

2020-11-03 18:57 UTC, Cjkjvfnby commented on HomeWork1/Tests/test_task02.py
> +        self.assertEqual(check_fibonacci(self.empty_sequence), False)
inline `self.empty_sequence`  and other variables.  It is much easier to check tests when data is located inside the test.

Pycharm:
![image](https://user-images.githubusercontent.com/171597/98028381-15977900-1e1f-11eb-8b87-596b941ed3dc.png)

2020-11-04 19:25 UTC, ivanzuev78 commented on HomeWork1/Tasks/task02.py
> +def check_fibonacci(data: Sequence) -> bool:
I changed it because of unittest. It can't work with "Sequence[int]". But it works without such annotation. I don't know why.

2020-11-04 19:31 UTC, Cjkjvfnby commented on HomeWork1/Tasks/task02.py
> +def check_fibonacci(data: Sequence) -> bool:
>  It can't work with "Sequence[int]".

Show logs.     Probably older Python version is used.

2020-11-04 19:31 UTC, ivanzuev78 commented on HomeWork1/Tasks/task02.py
> +def check_fibonacci(data: Sequence) -> bool:
![Снимок1](https://user-images.githubusercontent.com/63249816/98159364-7e4d2700-1eed-11eb-888a-340c03a980d1.PNG)
![Снимок](https://user-images.githubusercontent.com/63249816/98159374-84db9e80-1eed-11eb-934c-8ad874fe96d7.PNG)

2020-11-04 19:34 UTC, ivanzuev78 commented on HomeWork1/Tasks/task02.py
> +def check_fibonacci(data: Sequence) -> bool:
![Снимок1](https://user-images.githubusercontent.com/63249816/98159492-c409ef80-1eed-11eb-9a6a-4905993f3a66.PNG)

----------------------------------------------------------------------------------

![Снимок](https://user-images.githubusercontent.com/63249816/98159502-c704e000-1eed-11eb-850c-159df29a850d.PNG)

2020-11-04 19:40 UTC, Cjkjvfnby commented on HomeWork1/Tasks/task02.py
> +def check_fibonacci(data: Sequence) -> bool:
Remove `from collections import Sequence`

Use Pycharm quick fix to find proper import

2020-11-05 12:58 UTC, ivanzuev78 commented on HomeWork1/Tasks/task02.py
> +def check_fibonacci(data: Sequence) -> bool:
Thanks. It works. 
I used "from typing import Sequence" and its ok.

2020-11-05 18:13 UTC, Cjkjvfnby approved these changes

2020-11-06 04:43 UTC, merged