Homework 4 task 1
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #22
Opened 2020-11-13 18:18 UTC by ivanzuev78

Homework 4 task 1 done

2020-11-14 10:12 UTC, Cjkjvfnby requested changes

2020-11-14 10:12 UTC, Cjkjvfnby commented on HomeWork_4/task_2_mock_input.py
> +def count_dots_on_i(url: str) -> int:
It is not related to task1.

2020-11-14 10:12 UTC, Cjkjvfnby commented on HomeWork_4/test_task_1.py
> +
Please don't add an empty line between the function and its body.  

Empty lines supposed to visually split block, so you can find there next function is started.  When page is full of empty lines, it is vety hard to do it.

Lets remove all emty lines in the functin bodyies in all future PRs.

2020-11-14 10:12 UTC, Cjkjvfnby commented on HomeWork_4/test_task_1.py
> +    assert read_magic_number("data.txt") is True
`input_int_1_true` is not used, "data.txt" is hardcoded.  What can we do about this two facts?

2020-11-14 10:12 UTC, Cjkjvfnby commented on HomeWork_4/task_1_read_file.py
> +In case of any error, a ValueError should be thrown.
`ValueError should be thrown`  means that you should do a specific action in case of error.  `raise ValueError(???)`  

Which bad things can happen here?  Tell me about it via tests.

2020-11-14 10:12 UTC, Cjkjvfnby commented on HomeWork_4/task_1_read_file.py
> +You will learn:
Have you learned all of this?

2020-11-14 14:21 UTC, ivanzuev78 commented on HomeWork_4/task_2_mock_input.py
> +def count_dots_on_i(url: str) -> int:
The base brunch was wrong. Now it is ok.

2020-11-14 14:23 UTC, ivanzuev78 commented on HomeWork_4/test_task_1.py
> +
I think about it periodically. Thank you for your comment.

2020-11-14 14:54 UTC, ivanzuev78 commented on HomeWork_4/test_task_1.py
> +    assert read_magic_number("data.txt") is True
We can take "data.txt" from the fixture.

2020-11-14 14:58 UTC, ivanzuev78 commented on HomeWork_4/task_1_read_file.py
> +In case of any error, a ValueError should be thrown.
Done

2020-11-14 14:58 UTC, ivanzuev78 commented on HomeWork_4/task_1_read_file.py
> +You will learn:
Now I learned.

2020-11-14 16:38 UTC, Cjkjvfnby requested changes

2020-11-14 16:38 UTC, Cjkjvfnby commented on HomeWork_4/task_1_read_file.py
> +                raise ValueError("First line must be int or float!")
You don't need to check and raise here, you can raise it in `string_is_digit`

2020-11-14 16:38 UTC, Cjkjvfnby commented on HomeWork_4/task_1_read_file.py
> +            return True if 1 <= float(first_line) < 3 else False
You have float logic in two places. 
You can have  helper function that will do both value validation and return expecting value.

2020-11-14 16:38 UTC, Cjkjvfnby commented on HomeWork_4/test_task_1.py
> +
Please remove empty lines here too.

2020-11-14 19:02 UTC, ivanzuev78 commented on HomeWork_4/test_task_1.py
> +
Done.

2020-11-14 19:08 UTC, ivanzuev78 commented on HomeWork_4/task_1_read_file.py
> +            return True if 1 <= float(first_line) < 3 else False
Yes, code looks better after such refactoring.

2020-11-14 19:09 UTC, ivanzuev78 commented on HomeWork_4/task_1_read_file.py
> +                raise ValueError("First line must be int or float!")
Seems good.

2020-11-14 20:57 UTC, Cjkjvfnby requested changes

2020-11-14 20:57 UTC, Cjkjvfnby commented on HomeWork_4/task_1_read_file.py
> +        return float(input_from_file)
```
if number in an interval [1, 3)
```
This looks like int for me.   So let's change it to int.

2020-11-15 08:11 UTC, ivanzuev78 commented on HomeWork_4/task_1_read_file.py
> +        return float(input_from_file)
Ok, I'll change it. 
But I suppose it should be a float number. In the task, there is a link to Wikipedia, where the first sentence is "In mathematics, a (real) interval is a set of real numbers that contains **all real numbers lying between any two numbers of the set**."

2020-11-15 10:30 UTC, Cjkjvfnby commented on HomeWork_4/task_1_read_file.py
> +        return float(input_from_file)
There is no correct answer.  You will hit the ambigouty each time.  Sometime it is easy to notice it, sometimes it is hidden. 

There are 2 main directions to deal with it. 
1) Ask before starting task. 
2) Prepare for the change. Isolate this code:  move it to a separate function/class/module and make it easy to change your decision later. Choose the simpliest way and implement it.

2020-11-15 10:35 UTC, Cjkjvfnby approved these changes

2020-11-15 10:35 UTC, Cjkjvfnby commented on HomeWork_4/test_task_1.py
> +def test_read_magic_number_input_int_numb_1(input_int_1_true):
Bonus task:  

Create a factory fixture (fixture that returns a function and cleanup after itself)

```
def test_...(content_creater)
    file_name = content_creater(b"1\nhello")
    assert read_magic_number(file_name ) is True
```

2020-11-15 13:14 UTC, ivanzuev78 commented on HomeWork_4/test_task_1.py
> +def test_read_magic_number_input_int_numb_1(input_int_1_true):
Challenge accepted!

2020-11-15 13:15 UTC, ivanzuev78 commented on HomeWork_4/task_1_read_file.py
> +        return float(input_from_file)
Interesting. Thanks for the advice.

2020-11-15 21:18 UTC, Cjkjvfnby commented on HomeWork_4/test_task_1.py
> +    os.remove(name_of_file)
What will happend if you will not call the wrapper or call it twice?

2020-11-18 19:34 UTC, ivanzuev78 commented on HomeWork_4/test_task_1.py
> +    os.remove(name_of_file)
If we will not call the wrapper, os.remove(name_of_file) will be crashed. It fixed.
If we will call the wrapper twice the second will overwrite the first.

2020-11-18 22:12 UTC, Cjkjvfnby commented on HomeWork_4/test_task_1.py
> +    os.remove(name_of_file)
You can generate random names and store all created files in a list, so you can remove them later.

2020-11-20 17:51 UTC, merged