Homework 4 task 3
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #23
Opened 2020-11-13 19:53 UTC by ivanzuev78

Homework 4 task 3 done

2020-11-14 10:15 UTC, Cjkjvfnby requested changes
This task is about tests.  Do we have any special cases?

2020-11-14 11:40 UTC, ivanzuev78 commented
> This task is about tests. Do we have any special cases?

Did you mean wrong input?

2020-11-14 14:27 UTC, Cjkjvfnby commented
It is not wrong (type str), it is special.

2020-11-14 14:51 UTC, Cjkjvfnby requested changes

2020-11-14 14:51 UTC, Cjkjvfnby commented on HomeWork_4/test_task_3.py
> +    with pytest.raises(
This test just checks how Python works. 

 If checking the argument type is not in requirements of function then there is no need to add a test for it.

2020-11-14 15:12 UTC, ivanzuev78 commented
The only special case I found was empty input.

2020-11-14 20:54 UTC, Cjkjvfnby requested changes
Please for each test check that other output is empty.

2020-11-15 10:20 UTC, Cjkjvfnby approved these changes

2020-11-15 13:17 UTC, merged