Homework 4 task 4
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #25
Opened 2020-11-14 11:45 UTC by ivanzuev78

Homework 4 task 4 done

2020-11-14 14:56 UTC, Cjkjvfnby requested changes

2020-11-14 14:56 UTC, Cjkjvfnby commented on HomeWork_4/task_4_doctest.py
> +     - Run doctest 'python -m doctest -v HomeWork_4/task_4_doctest.py'
Why do you need pytest installed?

2020-11-14 14:56 UTC, Cjkjvfnby commented on HomeWork_4/task_4_doctest.py
> +    >>> fizzbuzz(5)
Can I pass any integer here?

2020-11-14 14:56 UTC, Cjkjvfnby commented on .github/workflows/check.yaml
> +          python -m doctest -v HomeWork_4/task_4_doctest.py
What will happen when you merge this to Homework_4?

2020-11-14 18:20 UTC, ivanzuev78 commented on .github/workflows/check.yaml
> +          python -m doctest -v HomeWork_4/task_4_doctest.py
I know, that these changes change Homework_4, and I can't run other tests in Homework_4. I don't know how to separate workflows for different files. I'll change it back before merging.

2020-11-14 18:21 UTC, ivanzuev78 commented on HomeWork_4/task_4_doctest.py
> +    >>> fizzbuzz(5)
No. Only positive.

2020-11-14 18:46 UTC, ivanzuev78 commented on HomeWork_4/task_4_doctest.py
> +     - Run doctest 'python -m doctest -v HomeWork_4/task_4_doctest.py'
I thought that doctest is the part of pytest. But now I know that it is pythons inner package.

2020-11-14 20:45 UTC, Cjkjvfnby requested changes

2020-11-14 20:45 UTC, Cjkjvfnby commented on HomeWork_4/task_4_doctest.py
> +     - Run doctest 'python -m doctest -v HomeWork_4/task_4_doctest.py'
Do you have any idea, why it was added in the initial instruction?

2020-11-14 20:45 UTC, Cjkjvfnby commented on HomeWork_4/task_4_doctest.py
> +    >>> fizzbuzz(5)
Any other ideas?

2020-11-15 08:21 UTC, ivanzuev78 commented on HomeWork_4/task_4_doctest.py
> +     - Run doctest 'python -m doctest -v HomeWork_4/task_4_doctest.py'
We should run doctest with the help of pytest?

2020-11-15 10:39 UTC, Cjkjvfnby commented on HomeWork_4/task_4_doctest.py
> +     - Run doctest 'python -m doctest -v HomeWork_4/task_4_doctest.py'
Since you already have `pytest` in your project, it will be a good idea to check if it can run other tests.

What do you think is better?  Have a single command to run all tests or 2 separate commands to run all tests?

2020-11-18 19:04 UTC, ivanzuev78 commented on HomeWork_4/task_4_doctest.py
> +    >>> fizzbuzz(5)
If input would be very big (I tried 999999999999), you will have MemoryError.

2020-11-18 19:15 UTC, ivanzuev78 commented on HomeWork_4/task_4_doctest.py
> +     - Run doctest 'python -m doctest -v HomeWork_4/task_4_doctest.py'
Of course, one command is better. But I don't know it now. I want to read documentation, but I don't have enough time.

2020-11-18 19:24 UTC, Cjkjvfnby commented on HomeWork_4/task_4_doctest.py
> +     - Run doctest 'python -m doctest -v HomeWork_4/task_4_doctest.py'
https://lmgtfy.app/?q=how+to+run+doctests+with+pytest

2020-11-18 19:26 UTC, Cjkjvfnby approved these changes

2020-11-18 19:37 UTC, merged