Homework 4 task 2
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #26
Opened 2020-11-15 17:08 UTC by ivanzuev78

2020-11-15 21:32 UTC, Cjkjvfnby requested changes

2020-11-15 21:32 UTC, Cjkjvfnby commented on HomeWork_4/task_2_mock_input.py
> +            sum(1 for char in line.decode() if char == "i")
Check `str` methods.

2020-11-15 21:32 UTC, Cjkjvfnby commented on HomeWork_4/test_task_2.py
> +    url = "https://example.com/"
Next time please include that task definition to PR. GitHub does not allow to leve a comments on code that was not changed.

> Test should use Mock instead of real network interactions.  

What is this about?

2020-11-15 21:32 UTC, Cjkjvfnby commented on HomeWork_4/test_task_2.py
> +    urllib.request.urlopen = MagicMock(
How do you restore `urllib.request.urlopen` state after test?  (This was mentioned in a  lecture)

2020-11-18 18:28 UTC, ivanzuev78 commented on HomeWork_4/test_task_2.py
> +    urllib.request.urlopen = MagicMock(
Using fixtures?

2020-11-18 18:29 UTC, ivanzuev78 commented on HomeWork_4/test_task_2.py
> +    url = "https://example.com/"
I had forgotten. Sorry. All fixed!

2020-11-18 18:29 UTC, ivanzuev78 commented on HomeWork_4/task_2_mock_input.py
> +            sum(1 for char in line.decode() if char == "i")
Changed.

2020-11-18 19:15 UTC, Cjkjvfnby requested changes

2020-11-18 19:15 UTC, Cjkjvfnby commented on HomeWork_4/test_task_2.py
> +    url = "https://example.com/"
Does this test do network interactions?

2020-11-18 19:15 UTC, Cjkjvfnby commented on HomeWork_4/test_task_2.py
> +    urllib.request.urlopen = MagicMock(
Yes.

2020-11-18 19:19 UTC, ivanzuev78 commented on HomeWork_4/test_task_2.py
> +    url = "https://example.com/"
Yes. It goes to "https://example.com/" and takes a request.

2020-11-18 19:20 UTC, ivanzuev78 commented on HomeWork_4/test_task_2.py
> +    urllib.request.urlopen = MagicMock(
Done.

2020-11-18 22:17 UTC, Cjkjvfnby requested changes

2020-11-18 22:17 UTC, Cjkjvfnby commented on HomeWork_4/test_task_2.py
> +def magic_mock_into_urlopen_return_url_error():
You are not supposed to write a fixture, you need to use one of the built-in pytest fixtures.

2020-11-22 09:22 UTC, Cjkjvfnby approved these changes

2020-11-22 15:52 UTC, merged