Homework 5 task_1 oop_1 done
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #29
Opened 2020-11-21 19:42 UTC by ivanzuev78

Homework 5 task_1 oop_1 done

2020-11-22 21:54 UTC, Cjkjvfnby requested changes
Looks good, just minor comments.

2020-11-22 21:54 UTC, Cjkjvfnby commented on HomeWork_5/oop_1.py
> +        is_active - проверяет не истело ли время на выполнение задания,
`истело` -> `истлело`

2020-11-22 21:54 UTC, Cjkjvfnby commented on HomeWork_5/oop_1.py
> +        self.deadline = datetime.timedelta(days_to_do)
It is better to use keyword argument here.

2020-11-22 21:54 UTC, Cjkjvfnby commented on HomeWork_5/oop_1.py
> +    def do_homework(homework: Homework) -> Union[Homework, None]:
Check Optional in typing module

2020-11-22 21:54 UTC, Cjkjvfnby commented on HomeWork_5/oop_1.py
> +        print("You are late")
If a function returns something it is good practice to explicitly return None

2020-11-22 21:54 UTC, Cjkjvfnby commented on HomeWork_5/test_oop_1.py
> +    yield teacher
I'd recommend inlining the variable.  Here and in other cases.

2020-11-22 21:54 UTC, Cjkjvfnby commented on HomeWork_5/test_oop_1.py
> +    expired_homework = Teacher.create_homework("Learn functions", 1)
Are you sure it is expired?

2020-11-22 21:54 UTC, Cjkjvfnby commented on HomeWork_5/test_oop_1.py
> +    monkeypatch.setattr(datetime, "datetime", new_datetime)
You can mock function directly, does not need to do it with the whole module

```python
monkeypatch.setattr(datetime.datetime, "now", lambda: new_time)
```

2020-11-22 21:54 UTC, Cjkjvfnby commented on HomeWork_5/test_oop_1.py
> +    assert student.do_homework(expired_homework) is expired_homework
What else can we check for `do_homework`?

2020-11-23 03:37 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    yield teacher
Done

2020-11-23 03:38 UTC, ivanzuev78 commented on HomeWork_5/oop_1.py
> +        is_active - проверяет не истело ли время на выполнение задания,
I suppose `истекло`

2020-11-23 03:50 UTC, ivanzuev78 commented on HomeWork_5/oop_1.py
> +        self.deadline = datetime.timedelta(days_to_do)
Done

2020-11-23 03:51 UTC, ivanzuev78 commented on HomeWork_5/oop_1.py
> +        print("You are late")
I will know. Done.

2020-11-23 03:53 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    expired_homework = Teacher.create_homework("Learn functions", 1)
I mixed this word up with the "expected".

2020-11-23 03:58 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    monkeypatch.setattr(datetime, "datetime", new_datetime)
I tried to do something like this, but it doesn't works.
```
>       monkeypatch.setattr(datetime.datetime, "now", lambda: new_time)
E       TypeError: can't set attributes of built-in/extension type 'datetime.datetime'
```

2020-11-23 04:02 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    assert student.do_homework(expired_homework) is expired_homework
I suppose the deadline.

2020-11-23 18:40 UTC, Cjkjvfnby commented on HomeWork_5/test_oop_1.py
> +    monkeypatch.setattr(datetime, "datetime", new_datetime)
```
a = []  # datatime
b = a  # reference in you module to datetime (during import)
c = []   
a = c   # monkeypath datetime, but you module already has a link to original a.
```
Try something like this. You need to patch it in your module, not in the original module.
```
import HomeWork_5.oop_1 

monkeypatch.setattr(oop_1.datetime.datetime, "now", lambda: new_time) 
```

2020-11-23 18:45 UTC, Cjkjvfnby commented on HomeWork_5/test_oop_1.py
> +    assert student.do_homework(expired_homework) is expired_homework
Does this function have side effects?

2020-11-23 18:46 UTC, Cjkjvfnby requested changes
Please check my last comments.

2020-11-25 17:22 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    monkeypatch.setattr(datetime, "datetime", new_datetime)
I suppose that is the answer:
https://stackoverflow.com/questions/4481954/trying-to-mock-datetime-date-today-but-not-working

2020-11-25 17:33 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    assert student.do_homework(expired_homework) is expired_homework
To tell the truth, I can't find side effects.

2020-11-25 21:46 UTC, Cjkjvfnby commented on HomeWork_5/test_oop_1.py
> +    assert student.do_homework(expired_homework) is expired_homework
What is the definition of side effects?  What is common examples?

2020-11-25 22:00 UTC, Cjkjvfnby commented on HomeWork_5/test_oop_1.py
> +    monkeypatch.setattr(datetime, "datetime", new_datetime)
Do you trust me or some strangers on the Internet?

Did you read all comments?
https://stackoverflow.com/a/20034516

2020-11-25 22:01 UTC, Cjkjvfnby requested changes
Please resolve the comments

2020-11-29 19:01 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    assert student.do_homework(expired_homework) is expired_homework
I didn' know about this meaning: https://en.wikipedia.org/wiki/Side_effect_(computer_science)
Example side effects include modifying a non-local variable, modifying a static local variable.
I suppose `student.do_homework(expired_homework)` can change `expired_homework`
I'll learn about side effects more.

2020-11-29 19:03 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    monkeypatch.setattr(datetime, "datetime", new_datetime)
It breakdown my brain.

2020-11-29 19:08 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    assert student.do_homework(expired_homework) is expired_homework
May be we should check, that after `do_homework(homework)` homework is the same?

2020-11-30 17:35 UTC, Cjkjvfnby commented on HomeWork_5/test_oop_1.py
> +    assert student.do_homework(expired_homework) is expired_homework
> Example side effects include modifying a non-local variable, modifying a static local variable, modifying a mutable argument passed by reference, performing I/O or calling other side-effect functions.

Which of this cases is present in the function?

2020-11-30 17:44 UTC, Cjkjvfnby requested changes
Question about side effects and a strange tests.

2020-11-30 17:44 UTC, Cjkjvfnby commented on HomeWork_5/test_oop_1.py
> +    assert hw_copy.created == homework.created
This looks like a test of the `copy.copy`.   It is already done here https://github.com/python/cpython/blob/master/Lib/test/test_copy.py#L160.  Why do we need an extra test for this class?

2020-12-02 17:09 UTC, ivanzuev78 commented on HomeWork_5/oop_1.py
> +    def do_homework(homework: Homework) -> Union[Homework, None]:
Done

2020-12-02 17:10 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    monkeypatch.setattr(datetime, "datetime", new_datetime)
Thanks for your explanations. Done.

2020-12-02 17:27 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    assert hw_copy.created == homework.created
As I understand, `student.do_homework(homework)` takes `homework` and can change this object globally. And we should check, that homework wasn't changed.

2020-12-09 20:39 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    assert student.do_homework(expired_homework) is expired_homework
I suppose it can modify a mutable argument passed by reference.

2020-12-16 20:41 UTC, Cjkjvfnby requested changes

2020-12-16 20:41 UTC, Cjkjvfnby commented on HomeWork_5/test_oop_1.py
> +    assert hw_copy.created == homework.created
> And we should check, that homework wasn't changed.

I don't think that it is required. 

You create an object with the `copy.copy`
```python
hw_copy = copy.copy(homework)
```

After that, you test that object created by `copy. copy` is a copy of the initial object.   This looks like testing `copy.copy`

2020-12-18 19:40 UTC, ivanzuev78 commented on HomeWork_5/test_oop_1.py
> +    assert hw_copy.created == homework.created
Yes. I understand now. And agree with you.

2020-12-18 20:51 UTC, Cjkjvfnby approved these changes

2020-12-19 07:08 UTC, merged