Task 03 done
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #3
Opened 2020-11-03 16:54 UTC by ivanzuev78

Задание выполнено, тест написан, вопросов нет.

2020-11-03 18:49 UTC, Cjkjvfnby requested changes
I have already left some comments on previous commit, can you check them?

Search in email. If it does not help, find all commits to this file in master and check all commits in history.

2020-11-03 18:49 UTC, Cjkjvfnby commented on HomeWork1/Tests/test_task03.py
> +        with open("data_test_task03_min1_max9.txt", "w") as f:
Please make a helper function.  It may accept a list of ints and file path and create a file.  In that case it will be easy to see which values are tested.    

Keep in mind that you dont need a lot of values in tests.  I' recommend limiting it with 3.

2020-11-05 17:10 UTC, ivanzuev78 commented on HomeWork1/Tests/test_task03.py
> +        with open("data_test_task03_min1_max9.txt", "w") as f:
All done.

2020-11-05 18:04 UTC, Cjkjvfnby requested changes

2020-11-05 18:04 UTC, Cjkjvfnby commented on HomeWork1/Tasks/task03.py
> +            if int(line) > max_numb:
You can do `elif` here too.  No need to process first line twice.

2020-11-05 18:04 UTC, Cjkjvfnby commented on HomeWork1/Tests/test_task03.py
> +        self.assertEqual(
Please provide an output example.  (Modify test that it fails for example.)

2020-11-07 19:38 UTC, ivanzuev78 commented on HomeWork1/Tests/test_task03.py
> +        self.assertEqual(
I don't understand what you mean.

2020-11-08 06:39 UTC, ivanzuev78 commented on HomeWork1/Tasks/task03.py
> +            if int(line) > max_numb:
Done

2020-11-08 12:21 UTC, Cjkjvfnby commented on HomeWork1/Tests/test_task03.py
> +        self.assertEqual(
The output is a result of the test.   Something that printed to logs after the test fails.  

Nevermind, I alredy found it out.

2020-11-08 12:26 UTC, Cjkjvfnby approved these changes

2020-11-08 15:23 UTC, closed without merging