Homework 5 task 2 save original info
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #30
Opened 2020-11-22 07:37 UTC by ivanzuev78

I have some problems.

2020-11-22 07:41 UTC, ivanzuev78 commented on HomeWork_5/test_task_2_save_original_info.py
> +    init_decorated_func = original_func(1, 2)
I have to call original_func to init it and rewrite __doc__ and __name__.
Is there any way to rewrite __doc__ and __name__ without calling original_func?

2020-11-23 19:07 UTC, Cjkjvfnby requested changes

2020-11-23 19:07 UTC, Cjkjvfnby commented on HomeWork_5/test_task_2_save_original_info.py
> +    init_decorated_func = original_func(1, 2)
1) use insert code action for function names  `__doc__` (click edit on this message to see markdown)
2) google your question

2020-11-23 19:15 UTC, Cjkjvfnby commented on HomeWork_5/test_task_2_save_original_info.py
> +    result_from_original_func = decorated_func.__original_func(1, 2, 3, 4)
Is it the same function or a different one?

2020-11-25 16:25 UTC, ivanzuev78 commented on HomeWork_5/test_task_2_save_original_info.py
> +    init_decorated_func = original_func(1, 2)
1. Thanks
2. Ok

2020-11-25 17:06 UTC, ivanzuev78 commented on HomeWork_5/test_task_2_save_original_info.py
> +    result_from_original_func = decorated_func.__original_func(1, 2, 3, 4)
What function do you mean?
If called function, it is non-decorated `original_func`.

2020-11-25 17:31 UTC, Cjkjvfnby requested changes

2020-11-25 17:31 UTC, Cjkjvfnby commented on HomeWork_5/test_task_2_save_original_info.py
> +    result_from_original_func = decorated_func.__original_func(1, 2, 3, 4)
You have 
1. origin al function
1. decorated function
1. function that can be accessed by __original_func

Are 1 and 3 the same?  

For example, different functions can produce the same result.  
max(0, 0) == min(0, 0)

I task you need to check that 3 is 1.   And checking the result is not a good way to do it.

2020-11-25 17:31 UTC, Cjkjvfnby commented on HomeWork_5/save_original_info.py
> +def my_decorator(func):
Is it a good name?  Does it describe the purpose of this function?

2020-11-25 18:51 UTC, ivanzuev78 commented on HomeWork_5/test_task_2_save_original_info.py
> +    result_from_original_func = decorated_func.__original_func(1, 2, 3, 4)
Implementation was not obvious to me, but it is done.

2020-11-25 18:52 UTC, ivanzuev78 commented on HomeWork_5/save_original_info.py
> +def my_decorator(func):
Of course not. Fixed.

2020-11-25 22:06 UTC, Cjkjvfnby approved these changes

2020-11-25 22:06 UTC, Cjkjvfnby commented on HomeWork_5/test_task_2_save_original_info.py
> +def test_print_result_original_func_saved(decorated_and_origin_funcs, capsys):
If you use fixture once you can just do it in the test.  And you can reuse some existiong function

```
def test_print_result_original_func_saved()
    decorated = print_result(sum)
    assert decorated_func.__original_func is sum
```

2020-11-26 18:10 UTC, ivanzuev78 commented on HomeWork_5/test_task_2_save_original_info.py
> +def test_print_result_original_func_saved(decorated_and_origin_funcs, capsys):
accepted.

2020-11-29 07:36 UTC, merged