Homework 6 task 1 counter done
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #31
Opened 2020-11-25 18:22 UTC by ivanzuev78

2020-11-29 16:25 UTC, Cjkjvfnby requested changes

2020-11-29 16:25 UTC, Cjkjvfnby commented on HomeWork_6/test_counter.py
> +    user, _, _ = decorated_class(), decorated_class(), decorated_class()
You can skip assignment.  And use decorated_class as an sample

2020-11-29 16:25 UTC, Cjkjvfnby commented on HomeWork_6/test_counter.py
> +    yield User
If you dont do a cleanup jus use more simple construction `return User`.

2020-11-29 16:25 UTC, Cjkjvfnby commented on HomeWork_6/test_counter.py
> +def test_instances_counter_reset_instances_counter(decorated_class):
Since you use only 2 test, you can remove fixture and just create a decorated class in each tests.

2020-11-29 16:25 UTC, Cjkjvfnby commented on HomeWork_6/test_counter.py
> +    class User:
Please decorate a class with a _counter=6 attribute. And check if this atttribute is still works after decoration.

2020-11-29 20:13 UTC, ivanzuev78 commented on HomeWork_6/test_counter.py
> +    class User:
It will not works after decoration because it will be overwritten. I'll try to save it.

2020-11-29 20:16 UTC, ivanzuev78 commented on HomeWork_6/test_counter.py
> +    user, _, _ = decorated_class(), decorated_class(), decorated_class()
Done

2020-11-29 20:16 UTC, ivanzuev78 commented on HomeWork_6/test_counter.py
> +    yield User
Of course.

2020-11-29 20:16 UTC, ivanzuev78 commented on HomeWork_6/test_counter.py
> +def test_instances_counter_reset_instances_counter(decorated_class):
Okey

2020-11-30 17:55 UTC, Cjkjvfnby approved these changes

2020-12-02 17:03 UTC, merged