Homework 6 task 2 oop2
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #32
Opened 2020-11-29 19:53 UTC by ivanzuev78

2020-11-29 20:28 UTC, Cjkjvfnby requested changes

2020-11-29 20:28 UTC, Cjkjvfnby commented on HomeWork_6/oop_2.py
> +            if hw_result not in Teacher.homework_done[hw_result.homework]:
How else uniqueness of the element in the collection can be checked?

2020-11-29 20:28 UTC, Cjkjvfnby commented on HomeWork_6/oop_2.py
> +            Teacher.homework_done = defaultdict(list)
It is better to clear exiting collection when reassign it.  Someone can already saved a link to old one to the variable.

2020-11-29 20:28 UTC, Cjkjvfnby commented on HomeWork_6/oop_2.py
> +    def __init__(self, first_name: str, last_name: str):
Can you use power of inheritance here?  This code can be much simplier.

2020-11-29 20:28 UTC, Cjkjvfnby commented on HomeWork_6/test_oop_2.py
> +    homework_result = student.do_homework(homework, "done")
Way `done` is a value for a bad home work?

2020-11-29 20:28 UTC, Cjkjvfnby commented on HomeWork_6/test_oop_2.py
> +    advanced_python_teacher.check_homework(hw_result)
What the difference between this calls?
```
opp_teacher.check_homework(hw_result)
advanced_python_teacher.check_homework(hw_result)
```

2020-12-02 17:34 UTC, ivanzuev78 commented on HomeWork_6/oop_2.py
> +    def __init__(self, first_name: str, last_name: str):
Done.

2020-12-02 17:38 UTC, ivanzuev78 commented on HomeWork_6/test_oop_2.py
> +    homework_result = student.do_homework(homework, "done")
Сonsidering, how often I use this word...
You right, it is better to take another word.

2020-12-02 17:44 UTC, ivanzuev78 commented on HomeWork_6/test_oop_2.py
> +    advanced_python_teacher.check_homework(hw_result)
Different teachers check the same work. In this case, it is equal `Teacher.check_homework` because `check_homework` is static.

2020-12-02 17:48 UTC, ivanzuev78 commented on HomeWork_6/test_oop_2.py
> +    advanced_python_teacher.check_homework(hw_result)
I suppose I can do it much easier.

2020-12-02 17:49 UTC, ivanzuev78 commented on HomeWork_6/oop_2.py
> +            Teacher.homework_done = defaultdict(list)
Done

2020-12-02 17:56 UTC, ivanzuev78 commented on HomeWork_6/oop_2.py
> +            if hw_result not in Teacher.homework_done[hw_result.homework]:
We can use `set`.

2020-12-02 20:39 UTC, Cjkjvfnby requested changes

2020-12-02 20:39 UTC, Cjkjvfnby commented on HomeWork_6/oop_2.py
> +def task():
No need to create a special object for the docstring. 

If your task is a single function it looks ok to move the description to docstring.  But if you need to create a lot of objects you can leave it as a comment.  

Each pattern or recommendation is applicable to a specific context.  It may not be suitable for another context.

2020-12-02 20:39 UTC, Cjkjvfnby commented on HomeWork_6/oop_2.py
> +        if not homework.is_active():
Can you rewrite this function without not?

2020-12-02 20:39 UTC, Cjkjvfnby commented on HomeWork_6/oop_2.py
> +    def __init__(self, homework: Homework, solution: str, author: Student):
Do your code works with examples from the task?

2020-12-02 20:39 UTC, Cjkjvfnby commented on HomeWork_6/test_oop_2.py
> +    return Teacher.create_homework("Learn functions", 1)
Is it possible to create homework that is outdated from the beginning?

2020-12-02 20:39 UTC, Cjkjvfnby commented on HomeWork_6/test_oop_2.py
> +def test_check_homework_doesnt_stack_same_hw():
You can reuse existing fixtures in that test.

2020-12-02 20:39 UTC, Cjkjvfnby commented on HomeWork_6/test_oop_2.py
> +    Teacher.check_homework(hw_result)
What will happen if you add another homework (a different one) here. Will that test fail?

2020-12-02 20:39 UTC, Cjkjvfnby commented on HomeWork_6/test_oop_2.py
> +    assert Teacher.homework_done == defaultdict(list)
Do we have any other option to check if the collection is empty?

2020-12-16 17:02 UTC, ivanzuev78 commented on HomeWork_6/oop_2.py
> +        if not homework.is_active():
Of course!

2020-12-16 17:10 UTC, ivanzuev78 commented on HomeWork_6/oop_2.py
> +def task():
Thank you for the explanation.

2020-12-16 17:15 UTC, ivanzuev78 commented on HomeWork_6/oop_2.py
> +    def __init__(self, homework: Homework, solution: str, author: Student):
Yes, now.

2020-12-16 17:19 UTC, ivanzuev78 commented on HomeWork_6/test_oop_2.py
> +    return Teacher.create_homework("Learn functions", 1)
Of course, we can.

2020-12-16 17:23 UTC, ivanzuev78 commented on HomeWork_6/test_oop_2.py
> +def test_check_homework_doesnt_stack_same_hw():
Done

2020-12-16 17:29 UTC, ivanzuev78 commented on HomeWork_6/test_oop_2.py
> +    Teacher.check_homework(hw_result)
Yes, the test will fail. Added check for this case at the end of this test.

2020-12-16 17:32 UTC, ivanzuev78 commented on HomeWork_6/test_oop_2.py
> +    assert Teacher.homework_done == defaultdict(list)
Of course, we can.

2020-12-16 20:44 UTC, Cjkjvfnby approved these changes

2020-12-18 19:27 UTC, merged