Hw 7 task 1
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #33
Opened 2020-12-02 19:08 UTC by ivanzuev78

2020-12-02 21:01 UTC, Cjkjvfnby requested changes

2020-12-13 20:34 UTC, ivanzuev78 commented on HomeWork_7/test_task_1.py
> +    assert find_occurrences(tree, "elem") == 2
I changed this test. Now we have two keys and no one of them was counted.

2020-12-13 20:42 UTC, ivanzuev78 commented on HomeWork_7/test_task_1.py
> +@pytest.mark.parametrize("elem_to_search", ({1, "elem"}, {1: 2, 2: True}))
Test added.

2020-12-13 20:42 UTC, ivanzuev78 commented on HomeWork_7/hw1.py
> +        nonlocal counter
Yes

2020-12-15 18:50 UTC, Cjkjvfnby requested changes

2020-12-15 18:50 UTC, Cjkjvfnby commented on HomeWork_7/hw1.py
> +    def look_into_collection(collection_to_discover: Union[list, tuple, dict, set]):
https://www.oxfordlearnersdictionaries.com/definition/english/discover

2020-12-15 18:50 UTC, Cjkjvfnby commented on HomeWork_7/test_task_1.py
> +@pytest.mark.parametrize("elem_to_search", [{1, "elem"}, {1: 2, 2: True}])
What is the difference between hashable and unhashible elements in this task context?

2020-12-15 18:50 UTC, Cjkjvfnby commented on HomeWork_7/test_task_1.py
> +    assert find_occurrences(tree, "elem") == 0
`test_find_occurrences_element_in_key`  Do we found this elements?

2020-12-16 06:51 UTC, ivanzuev78 commented on HomeWork_7/test_task_1.py
> +    assert find_occurrences(tree, "elem") == 0
No. As I remember, we shouldn't search elements in keys.

2020-12-16 07:05 UTC, ivanzuev78 commented on HomeWork_7/test_task_1.py
> +@pytest.mark.parametrize("elem_to_search", [{1, "elem"}, {1: 2, 2: True}])
`set` doesn't accept hashable elements. 
I changed tests.

2020-12-16 07:11 UTC, ivanzuev78 commented on HomeWork_7/hw1.py
> +    def look_into_collection(collection_to_discover: Union[list, tuple, dict, set]):
Thank you.
Changed.

2020-12-16 20:51 UTC, Cjkjvfnby commented on HomeWork_7/test_task_1.py
> +    assert find_occurrences(tree, "elem") == 0
The test name should show me your intention.  `test_find_occurrences_element_in_key` means for me that we are searching in key.  If you write the test to show that element in key is ignored just name the test in that way.

2020-12-17 17:52 UTC, Cjkjvfnby commented on HomeWork_7/test_task_1.py
> +    assert find_occurrences(tree, "elem") == 0
@ivanzuev78 please fix it

2020-12-17 17:52 UTC, Cjkjvfnby approved these changes

2020-12-18 19:28 UTC, merged