Homework 7 task 2
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #34
Opened 2020-12-02 19:34 UTC by ivanzuev78

2020-12-02 21:14 UTC, Cjkjvfnby requested changes

2020-12-02 21:14 UTC, Cjkjvfnby commented on HomeWork_7/hw2.py
> +            print(real_typed_string)
Linter definitely should catch this.  Please check your settings.  Looks like you disable it in a much broader scope than needed.

2020-12-02 21:14 UTC, Cjkjvfnby commented on HomeWork_7/hw2.py
> +    def type_this_string(string_to_type):
What is the algorithmic complexity of this function?

2020-12-06 09:03 UTC, ivanzuev78 commented on HomeWork_7/hw2.py
> +    def type_this_string(string_to_type):
Didn't think about it. I suppose it is O(n).

2020-12-06 10:20 UTC, Cjkjvfnby commented on HomeWork_7/hw2.py
> +    def type_this_string(string_to_type):
Can it be better?

2020-12-06 12:36 UTC, ivanzuev78 commented on HomeWork_7/hw2.py
> +    def type_this_string(string_to_type):
It should be ok now.

2020-12-06 12:38 UTC, ivanzuev78 commented on HomeWork_7/hw2.py
> +            print(real_typed_string)
Yes, you're right. I fixed it.

2020-12-15 18:59 UTC, Cjkjvfnby requested changes
Please check which files are added to the commit.  There are to many of them.

2020-12-16 20:54 UTC, Cjkjvfnby approved these changes

2020-12-16 20:54 UTC, Cjkjvfnby commented on HomeWork_7/hw2.py
> +                chars_in_real_typed_string.pop(-1)
Please check `pop` signature.

2020-12-18 19:29 UTC, merged