Homework 7 task 3
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #37
Opened 2020-12-06 17:12 UTC by ivanzuev78

Done

2020-12-08 17:04 UTC, Cjkjvfnby requested changes

2020-12-08 17:04 UTC, Cjkjvfnby commented on HomeWork_7/hw3.py
> +        + [[board[i][2 - i] for i in range(3)]]
IMHO it is much easier to just write all 8 combination by hand.    
You can leave it as is.

2020-12-09 18:34 UTC, ivanzuev78 commented on .pre-commit-config.yaml
> +          - "--ignore=S101,W503"
I can't understand, what does it mean. Now I know, thanks.

2020-12-09 18:45 UTC, ivanzuev78 commented on HomeWork_7/hw3.py
> +        if all(map(lambda x: x == "x", row)):
Yes, it is much easier.

2020-12-16 07:32 UTC, ivanzuev78 commented on HomeWork_7/hw3.py
> +        return False
It was `Union[str, bool]`
It is `str` now.

2020-12-16 07:33 UTC, ivanzuev78 commented on HomeWork_7/hw3.py
> +        + [[board[i][2 - i] for i in range(3)]]
Agree with you.

2020-12-16 20:56 UTC, Cjkjvfnby approved these changes

2020-12-18 19:30 UTC, merged