Homework 8 task 2
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #39
Opened 2020-12-13 15:32 UTC by ivanzuev78

2020-12-13 17:25 UTC, Cjkjvfnby requested changes

2020-12-13 17:25 UTC, Cjkjvfnby commented on HomeWork_8/task_2.py
> +        self.conn = sqlite3.connect(database_name)
How do you close it?

2020-12-13 17:25 UTC, Cjkjvfnby commented on HomeWork_8/task_2.py
> +            self.cursor.execute(
You can do a select by table name and check if row is present ifstead of reading all tables.

2020-12-13 17:25 UTC, Cjkjvfnby commented on HomeWork_8/task_2.py
> +        names_field = list(map(lambda x: x[0], self.cursor.description))
do you need a list here?

2020-12-13 17:25 UTC, Cjkjvfnby commented on HomeWork_8/test_task_2.py
> +    conn = sqlite3.connect(database_name)
What is a better solution?

2020-12-23 17:46 UTC, ivanzuev78 commented on HomeWork_8/task_2.py
> +        names_field = list(map(lambda x: x[0], self.cursor.description))
No, we don't.

2020-12-23 18:05 UTC, ivanzuev78 commented on HomeWork_8/task_2.py
> +            self.cursor.execute(
Agree with you.
Done.

2020-12-23 18:06 UTC, ivanzuev78 commented on HomeWork_8/task_2.py
> +        self.conn = sqlite3.connect(database_name)
I didn't close it.
Now I close it after every request.

2020-12-23 18:29 UTC, ivanzuev78 commented on HomeWork_8/test_task_2.py
> +    conn = sqlite3.connect(database_name)
Should I mock `sqlite3.connect`?

2020-12-23 19:22 UTC, ivanzuev78 commented on HomeWork_8/test_task_2.py
> +    conn = sqlite3.connect(database_name)
Changed

2020-12-24 21:45 UTC, Cjkjvfnby approved these changes

2020-12-24 21:45 UTC, Cjkjvfnby commented on HomeWork_8/test_task_2.py
> +os.chdir(os.path.dirname(__file__))
See comment for task 10

2020-12-25 03:34 UTC, merged