Task 04 done without tests
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #4
Opened 2020-11-03 17:08 UTC by ivanzuev78

Задание выполнено.
Была мысль, что можно создать для каждого списка четырёхмерный массив, а потом поэлементно их сложить. Думал, может это будет эффективнее, но потом прикинул, что нам в любом случае потом по нему проходить и, скорее всего, это будет ресурсозатратнее. 

Тест не успел написать, так как вручную его писать долго, и не хотелось бы использовать алгоритм, который мы должны проверить в качестве создателя данных для теста.

2020-11-03 18:19 UTC, Cjkjvfnby requested changes
Tests are required.

2020-11-06 16:38 UTC, Cjkjvfnby requested changes

2020-11-06 16:38 UTC, Cjkjvfnby commented on HomeWork1/Tests/test_task04.py
> +    def test_check_sum_of_four(self):
This test has N == 2.  Do we need to test with another N? 

This test has a positive number as output,  can we have another output?

2020-11-07 19:47 UTC, ivanzuev78 commented on HomeWork1/Tests/test_task04.py
> +    def test_check_sum_of_four(self):
Yes. It can be zero.

2020-11-07 23:01 UTC, Cjkjvfnby approved these changes

2020-11-08 06:38 UTC, merged