Homework 9 task 1
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #40
Opened 2020-12-13 18:06 UTC by ivanzuev78

2020-12-13 23:16 UTC, Cjkjvfnby requested changes

2020-12-13 23:16 UTC, Cjkjvfnby commented on HomeWork_9/hw1.py
> +        yield int(opened_files[current_list_to_take_numb].pop(0))
What is a complexity of this operation?

2020-12-16 18:01 UTC, ivanzuev78 commented on HomeWork_9/hw1.py
> +        yield int(opened_files[current_list_to_take_numb].pop(0))
I suppose the complexity of this operation is O(n) for 1 execution. And it becomes O(n^2) after 'n' executions.
But we can use reversed list, so `pop(-1)` is O(1), and the whole algorithm becomes O(n).

2020-12-17 17:27 UTC, Cjkjvfnby requested changes
It is expected that we don't read the whole file into a memory.

2020-12-18 20:40 UTC, ivanzuev78 commented on HomeWork_9/hw1.py
> +            opened_files.append(list(reversed(list(f))))
I just thought that iterator should remember its state when it was created (it was said in the lecture, that it shouldn't depend on changes in outer scopes). 
It doesn't read the whole file now.

2020-12-19 11:00 UTC, Cjkjvfnby requested changes

2020-12-19 20:43 UTC, ivanzuev78 commented on HomeWork_9/hw1.py
> +        with open(file_manager_dict["filename"], "r") as f:
Yes, I know. I thought we should close the file after every reading. 
I suppose if we don't close file after every reading no one can change it. So it implements the iteration protocol.

2020-12-21 20:51 UTC, Cjkjvfnby approved these changes

2020-12-21 20:51 UTC, Cjkjvfnby commented on HomeWork_9/hw1.py
> +            raise ValueError("String is not a numb")
Since VvalueError raised anyway we don't need checks.
```suggestion
        opened_files[filename]["numb"] = int(numb[:-1])
```

2020-12-22 15:30 UTC, merged