Homework 9 task 2
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #41
Opened 2020-12-13 19:07 UTC by ivanzuev78

2020-12-13 23:17 UTC, Cjkjvfnby requested changes
> Do it both ways: as a class and as a generator.

Does both solution have the same behavior?

2020-12-16 18:35 UTC, ivanzuev78 commented
I suppose they have a little bit different behaviour, but they have the same result. 
I don't know how we catch an exception in the function context manager.

2020-12-17 17:30 UTC, Cjkjvfnby commented
> but they have the same result

Could you please add 2 tests

```python
def test_....():
    with XXX(Exception):
        raise IndexError("Raise IndexError from SuppressorClass")
```

2020-12-17 17:30 UTC, Cjkjvfnby requested changes

2020-12-17 17:30 UTC, Cjkjvfnby commented on HomeWork_9/test_task_2.py
> +    assert True
Why do you need it?

2020-12-18 20:48 UTC, ivanzuev78 commented on HomeWork_9/test_task_2.py
> +    assert True
Just for beauty.
We don't need it at all.

> > but they have the same result
> 
> Could you please add 2 tests
> 
> ```python
> def test_....():
>     with XXX(Exception):
>         raise IndexError("Raise IndexError from SuppressorClass")
> ```

Hmmm, SuppressorClass doesn't work, but suppressor_function works. Interesting.

2020-12-18 20:54 UTC, ivanzuev78 commented on HomeWork_9/test_task_2.py
> +    assert True
I understand now. I hadn't thought about inheritance. 
Now it should work correctly.

2020-12-18 21:07 UTC, Cjkjvfnby approved these changes

2020-12-19 07:09 UTC, merged