Homework 9 task 3
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #42
Opened 2020-12-13 20:24 UTC by ivanzuev78

2020-12-13 23:23 UTC, Cjkjvfnby requested changes

2020-12-13 23:23 UTC, Cjkjvfnby commented on HomeWork_9/hw3.py
> +        if file[-len(file_extension) :] == file_extension:
What string method can be used instead of that? 

Does Python have specially created method to work with extensions?

2020-12-13 23:23 UTC, Cjkjvfnby commented on HomeWork_9/hw3.py
> +                    for _ in f:
Can we simplify it?

2020-12-18 21:02 UTC, ivanzuev78 commented on HomeWork_9/hw3.py
> +                    for _ in f:
Yes. 
Simplified.

2020-12-18 21:15 UTC, ivanzuev78 commented on HomeWork_9/hw3.py
> +        if file[-len(file_extension) :] == file_extension:
Yes, it has.

2020-12-18 21:25 UTC, Cjkjvfnby approved these changes

2020-12-19 07:10 UTC, merged