Homework 10 task 1
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #43
Opened 2020-12-24 00:58 UTC by ivanzuev78

2020-12-24 21:41 UTC, Cjkjvfnby requested changes

2020-12-24 21:41 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +        json.dump(data, file)
I recommend adding indent=4 for readability.

2020-12-24 21:41 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +                itertools.chain(*all_companies_dicts_before_parsing_its_page),
What argument type is expected here?

2020-12-24 21:41 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +    bsObj = BeautifulSoup(html.text, "html.parser")
This name looks as strange as https://ru.wikipedia.org/wiki/%D0%91%D0%9E%D0%A7_%D1%80%D0%92%D0%A4_260602

You can name it `content`.

2020-12-24 21:41 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +    for j, comp in zip(bsObj.find_all("img"), companies):
j stands for jif?  https://time.com/5791028/how-to-pronounce-gif/

2020-12-24 21:41 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +        if re.match("https://pproxy.markets.businessinsider.com", j["src"]) != "None":
`!= "None"`  Does re.match return a string?

2020-12-24 21:41 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +    top_10 = list(sorted(data, key=lambda x: x["price_in_USD"])[-10:])
What is the return type of `sorted`?

2020-12-24 21:41 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +    top_10 = list(sorted(data, key=lambda x: x["price_in_USD"])[-10:])
https://docs.python.org/3/library/heapq.html#heapq.nlargest

2020-12-24 21:41 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +        company["price_in_RUB"] = company["price_in_USD"] * usd_to_rub
What is bad with this code (expression itself is ok)?

2020-12-24 21:41 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +def get_top_10_min_pe(data: List[Dict]) -> List[Dict]:
Complexity overflow in a single expression. 

Please split it into chunks by extracting values to the variables.

2020-12-24 21:41 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +            lambda x: True if "P/E" in x else False,
Can you simplify the expression?

Which module can give us simple replacement for such types of lambda?

2020-12-24 21:41 UTC, Cjkjvfnby commented on HomeWork_10/test_HW_10_task_1.py
> +os.chdir(os.path.dirname(__file__))
I'd prefer moving this to a fixture.  
You can set the scope module and set autouse, or do it in fixtures that reads the file.

2021-01-06 12:59 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +        json.dump(data, file)
I don't understand, what you mean.

2021-01-06 14:22 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +                itertools.chain(*all_companies_dicts_before_parsing_its_page),
Iterable is expected. 
all_companies_dicts_before_parsing_its_page is List[List[Dict]].
But we need List[Dict]. So, with itertools.chain we unpack inner lists.

2021-01-06 14:24 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +    bsObj = BeautifulSoup(html.text, "html.parser")
You right!

2021-01-06 14:28 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +    for j, comp in zip(bsObj.find_all("img"), companies):
J is jpg. I wanted to change it later but had forgotten.

2021-01-06 14:34 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +        if re.match("https://pproxy.markets.businessinsider.com", j["src"]) != "None":
No.

2021-01-06 14:40 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +    top_10 = list(sorted(data, key=lambda x: x["price_in_USD"])[-10:])
Return type of `sorted` is an iterator. Using `list` was unnecessary. 
I don't know about `nlargest`.
Thanks.

2021-01-06 14:51 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +        company["price_in_RUB"] = company["price_in_USD"] * usd_to_rub
I need one more hint.

2021-01-06 15:25 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +        company["price_in_RUB"] = company["price_in_USD"] * usd_to_rub
Maybe we should take `nlargest` by price in rub?

2021-01-06 15:27 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +def get_top_10_min_pe(data: List[Dict]) -> List[Dict]:
You meant something like these: `def get_top_10_min_pe(*data: Dict)` ?

2021-01-06 15:35 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +            lambda x: True if "P/E" in x else False,
Expression simplified.
I don't remember the module, but I remember, how I can simplify this lambda.

2021-01-06 15:35 UTC, ivanzuev78 commented on HomeWork_10/test_HW_10_task_1.py
> +os.chdir(os.path.dirname(__file__))
Done.

2021-01-10 05:52 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +        json.dump(data, file)
https://docs.python.org/3/library/json.html#json.dump

2021-01-10 06:04 UTC, Cjkjvfnby requested changes
Some small fixes required.

See https://docs.python.org/3/library/operator.html?highlight=operator#operator.contains

2021-01-10 06:04 UTC, Cjkjvfnby commented on HomeWork_10/task_threads.py
> +        company["price_in_RUB"] = company["price_in_USD"] * usd_to_rub
It is duplicated.

2021-01-10 17:07 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +        json.dump(data, file)
If I only know about this, my life would be much easier.

2021-01-10 17:23 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +                itertools.chain(*all_companies_dicts_before_parsing_its_page),
Seems good.

2021-01-10 18:08 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +                itertools.chain(*all_companies_dicts_before_parsing_its_page),
But `pool.map` trying to send values from all iterators to the function.
TypeError: get_info_from_company_url() takes 1 positional argument but 10 were given
I tried:
1) pool.map(get_info_from_company_url, all_companies_dicts_before_parsing_its_page)
2) pool.map(get_info_from_company_url, *all_companies_dicts_before_parsing_its_page)

2021-01-10 18:15 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +        company["price_in_RUB"] = company["price_in_USD"] * usd_to_rub
Hmm, it is not obvious to me.

2021-01-11 17:30 UTC, ivanzuev78 commented on HomeWork_10/task_threads.py
> +        company["price_in_RUB"] = company["price_in_USD"] * usd_to_rub
Oh, I am inattentive a little bit.

2021-01-11 17:31 UTC, ivanzuev78 commented
Unused function deleted.

2021-01-11 19:10 UTC, Cjkjvfnby approved these changes

2021-01-12 17:39 UTC, merged