Task 05 done
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #5
Opened 2020-11-03 18:13 UTC by ivanzuev78

Задание выполнено, тест написан, вопросов нет.

2020-11-03 18:34 UTC, Cjkjvfnby requested changes

2020-11-03 18:34 UTC, Cjkjvfnby commented on HomeWork1/Tests/test_task05.py
> +        self.example_array = [1, 3, -1, -3, 5, 3, 6, 7]
Move this to the test.  Input can be a part of test.  Setup should be used only to share code betweeen multiple tests.

2020-11-03 18:34 UTC, Cjkjvfnby commented on HomeWork1/Tests/test_task05.py
> +        self.assertEqual(find_maximal_subarray_sum([1, 3, -1, -3, 5, 3, 6, 7], 3), 16)
I expect at least one more test. (Hint it will fail.)

2020-11-07 20:07 UTC, ivanzuev78 commented on HomeWork1/Tests/test_task05.py
> +        self.assertEqual(find_maximal_subarray_sum([1, 3, -1, -3, 5, 3, 6, 7], 3), 16)
I had made one more test. But I don't understand which test (with the good input) will fail.

2020-11-07 23:02 UTC, Cjkjvfnby requested changes

2020-11-07 23:02 UTC, Cjkjvfnby commented on HomeWork1/Tests/test_task05.py
> +        self.assertEqual(find_maximal_subarray_sum([1, 3, -1, -3, 5, 3, 6, 7], 3), 16)
What about empty list?

2020-11-08 07:19 UTC, ivanzuev78 commented on HomeWork1/Tests/test_task05.py
> +        self.assertEqual(find_maximal_subarray_sum([1, 3, -1, -3, 5, 3, 6, 7], 3), 16)
I thought about it. I didn't know how I can handle the exception. Now I guess.

2020-11-08 12:30 UTC, Cjkjvfnby approved these changes
All comments are optional

2020-11-08 12:30 UTC, Cjkjvfnby commented on HomeWork1/Tasks/task05.py
> +    if len(nums) == 0:
`If not nums`

2020-11-08 12:30 UTC, Cjkjvfnby commented on HomeWork1/Tests/test_task05.py
> +        find_maximal_subarray_sum([], 10)
Is it a preferred way to check exception with unittests?

2020-11-08 15:17 UTC, merged