HomeWork_2 task_2 done
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #6
Opened 2020-11-06 13:26 UTC by ivanzuev78

Homework 2 task 2 done. 
As you advised, i had made test in the file with task.

2020-11-06 16:20 UTC, Cjkjvfnby requested changes

2020-11-06 16:20 UTC, Cjkjvfnby commented on HomeWork_2/hw2.py
> +    counter = {}
Check the collections module there are at least two better "dicts" for that case.

2020-11-06 16:20 UTC, Cjkjvfnby commented on HomeWork_2/hw2.py
> +        input_3 = [i for i in range(20)] + [i for i in range(19)] + [10]
Very complex, check, you can achieve the same test coverage with smalle input with out any generation.

2020-11-06 16:25 UTC, Cjkjvfnby commented on HomeWork_2/hw2.py
> +        self.assertEqual(major_and_minor_elem(input_2), (3, 2))
Joining multiple test to one considered a bad practice.  If first test failed, you dont know about others. 

Please move them to separate tests.

2020-11-08 13:37 UTC, ivanzuev78 commented on HomeWork_2/hw2.py
> +    counter = {}
Yes. Counter from collections is much more better. Thanks)

2020-11-08 13:39 UTC, ivanzuev78 commented on HomeWork_2/hw2.py
> +        input_3 = [i for i in range(20)] + [i for i in range(19)] + [10]
I suppose, its enought first two inputs to cover function.

2020-11-08 13:39 UTC, ivanzuev78 commented on HomeWork_2/hw2.py
> +        self.assertEqual(major_and_minor_elem(input_2), (3, 2))
Done.

2020-11-08 14:31 UTC, Cjkjvfnby requested changes

2020-11-08 14:31 UTC, Cjkjvfnby commented on HomeWork_2/hw2.py
> +    # for elem in counter:
What is this comment about?

2020-11-08 14:31 UTC, Cjkjvfnby commented on HomeWork_2/hw2.py
> +    # major_elem = None
What is this comment about?

2020-11-08 16:03 UTC, ivanzuev78 commented on HomeWork_2/hw2.py
> +    # for elem in counter:
Sorry, I had commented previos code and forgotten to delete it.

2020-11-08 16:06 UTC, ivanzuev78 commented on HomeWork_2/hw2.py
> +    # major_elem = None
I commented previous code and had forgotten to delete it

2020-11-08 16:27 UTC, Cjkjvfnby commented on HomeWork_2/hw2.py
> +    # major_elem = None
That kind of error could be catched by automated checks. For some reason checks were not run on this PR.

2020-11-08 16:27 UTC, Cjkjvfnby approved these changes

2020-11-08 17:01 UTC, merged