Hw 2 task 3
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #7
Opened 2020-11-07 08:36 UTC by ivanzuev78

Homework 2 task 3 done

2020-11-07 23:53 UTC, Cjkjvfnby requested changes

2020-11-07 23:53 UTC, Cjkjvfnby commented on HomeWork_2/hw3.py
> +        if len(args) == 1:
It will be more convenient to have this check before cycle.

2020-11-07 23:53 UTC, Cjkjvfnby commented on HomeWork_2/hw3.py
> +            for end_of_array in combinations(*args[1:]):
There is a nice name in function programming for that:  tail

2020-11-08 15:28 UTC, ivanzuev78 commented on HomeWork_2/hw3.py
> +        if len(args) == 1:
Yes, I agree.

2020-11-08 15:29 UTC, ivanzuev78 commented on HomeWork_2/hw3.py
> +            for end_of_array in combinations(*args[1:]):
I'll memorize it))

2020-11-08 16:34 UTC, Cjkjvfnby requested changes

2020-11-08 16:34 UTC, Cjkjvfnby commented on HomeWork_2/hw3.py
> +        for i in args[0]:
Can you change this for- loop to list comprehension or geenrator expression?

2020-11-08 16:34 UTC, Cjkjvfnby commented on HomeWork_2/test_hw3.py
> +def test_combinations_example():
Have you covered all cases that can be in combinations?

2020-11-08 17:13 UTC, ivanzuev78 commented on HomeWork_2/test_hw3.py
> +def test_combinations_example():
Added 2 more tests.

2020-11-08 17:14 UTC, ivanzuev78 commented on HomeWork_2/hw3.py
> +        for i in args[0]:
Of course I can.

2020-11-08 21:18 UTC, Cjkjvfnby requested changes

2020-11-08 21:18 UTC, Cjkjvfnby commented on HomeWork_2/test_hw3.py
> +def test_combinations_example():
Need more. Check your implementation for ideas.

2020-11-11 20:54 UTC, ivanzuev78 commented on HomeWork_2/test_hw3.py
> +def test_combinations_example():
May be something like that?

2020-11-11 21:05 UTC, Cjkjvfnby approved these changes

2020-11-11 21:13 UTC, merged