Homework 2 task 4 done
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #8
Opened 2020-11-07 09:51 UTC by ivanzuev78

Homework 2 task 4 done

2020-11-08 00:00 UTC, Cjkjvfnby requested changes

2020-11-08 00:00 UTC, Cjkjvfnby commented on HomeWork_2/test_hw4.py
> +def test_cache_check_time():
Please add test for 

```python
def double(nums: List[int]) -> List[int]:
  return [x * 2 for x in nums]
```

2020-11-08 13:18 UTC, Cjkjvfnby commented on HomeWork_2/test_hw4.py
> +    time_start = time.time()
Time is not a reliable source for test information.   See the task description for an assertion example.

2020-11-08 15:56 UTC, ivanzuev78 commented on HomeWork_2/test_hw4.py
> +    time_start = time.time()
We use cache to save time and computing power. But if our cache func is slower than original func, its a reason to think about caches realisation. 
I always have other tests like example.

2020-11-08 15:58 UTC, ivanzuev78 commented on HomeWork_2/test_hw4.py
> +def test_cache_check_time():
No problem.

2020-11-08 15:58 UTC, ivanzuev78 commented on HomeWork_2/hw4.py
> +from collections.abc import Callable
Done

2020-11-08 18:16 UTC, Cjkjvfnby requested changes

2020-11-08 19:12 UTC, ivanzuev78 commented on HomeWork_2/test_hw4.py
> +    time_start = time.time()
I completely agree now.

2020-11-11 21:40 UTC, ivanzuev78 commented on HomeWork_2/test_hw4.py
> +def test_cache_check_time():
I had forgotten about hashability of some types. Now it should work correctly.

2020-11-11 22:44 UTC, Cjkjvfnby requested changes

2020-11-11 22:44 UTC, Cjkjvfnby commented on HomeWork_2/hw4.py
> +def hashable(users_input):
What is the difference between `object_is_cacheable` and `hashable`?

2020-11-11 22:44 UTC, Cjkjvfnby commented on HomeWork_2/hw4.py
> +
This empty lines inside else blocks looks strange, can you remove them?

2020-11-11 22:44 UTC, Cjkjvfnby commented on HomeWork_2/hw4.py
> +        if not hashable((*args, *kwargs)):
You can make something like this:
```python
key = make_key(*args, **kwargs)
if not key in results:
   results[key] = fun(*args, **kwargs)
return results[key]

```

2020-11-11 22:44 UTC, Cjkjvfnby commented on HomeWork_2/hw4.py
> +    if all(map(hashable, kwargs.values())):
You have lost keys.

please add test:  `foo(a=10) is foo(b=10)`

2020-11-12 07:19 UTC, ivanzuev78 commented on HomeWork_2/hw4.py
> +def hashable(users_input):
I'm so inattentive.

2020-11-12 07:20 UTC, ivanzuev78 commented on HomeWork_2/hw4.py
> +
Yes.

2020-11-12 07:34 UTC, ivanzuev78 commented on HomeWork_2/hw4.py
> +    if all(map(hashable, kwargs.values())):
Yes. Now its should be ok.

2020-11-12 07:40 UTC, ivanzuev78 commented on HomeWork_2/hw4.py
> +        if not hashable((*args, *kwargs)):
Yes. It would be better.

2020-11-12 07:41 UTC, ivanzuev78 commented on HomeWork_2/hw4.py
> +    if all(map(hashable, kwargs.values())):
Added test "test_cache_same_args_different_kwargs"

2020-11-12 07:42 UTC, ivanzuev78 commented on HomeWork_2/hw4.py
> +    if all(map(hashable, kwargs.values())):
Added test "test_cache_same_args_different_kwargs"

2020-11-12 17:26 UTC, Cjkjvfnby approved these changes

2020-11-12 17:26 UTC, Cjkjvfnby commented on HomeWork_2/test_hw4.py
> +def test_double_cache():
Funny name.

2020-11-12 17:27 UTC, merged