Homework 2 task 1 done
ivanzuev78/IvanZuev_EPAM_autumn_2020 pull request #9
Opened 2020-11-07 16:18 UTC by ivanzuev78

Homework 2 task 1 done

2020-11-08 13:00 UTC, Cjkjvfnby requested changes

2020-11-08 14:14 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +        for letter in word:
def reader(file_path, output='WORDS') returns words if format: [['o', 'n', 'e',] , ['t', 'w', 'o'], ['w', 'o', 'r', 'd',]], so we have to put together all the letters to get whole word.

2020-11-08 14:16 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +    text.sort(key=lambda word: len(frozenset(word)), reverse=True)
I wanted to use dict to count, but later I changed my mind and had forgotten to change it back to "set". Now it changed.

2020-11-08 14:37 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +        if len(i) > 1:
Yes. When we parse non-ASCII letters, we save them as '\\u00ab'. So, len of such symbols is more than 1.

2020-11-08 14:38 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +        if i in ".,:;-()!?":
Done

2020-11-08 14:39 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +    text = reader(file_path, output="WORDS")
Do you mean something like that?
![reader](https://user-images.githubusercontent.com/63249816/98467966-527dba00-21e9-11eb-96d4-cc8b9bc6f1d8.PNG)

2020-11-08 15:06 UTC, ivanzuev78 commented on HomeWork_2/test_hw1.py
> +    os.remove("test_text.txt")
Hmm. Didn't think about it. 
I suppose OS can forbidden us to do it? 
Do you mean something like that?

2020-11-08 15:09 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +        if len(i) > 1:
Done

2020-11-08 15:11 UTC, ivanzuev78 commented on HomeWork_2/test_hw1.py
> +    # Генерирую такой большой массив, потому что надо минимум 10 слов с уникальными символами
https://github.com/ivanzuev78/IvanZuev_EPAM_autumn_2020/pull/9#discussion_r519388381
It was the first and the last time!

2020-11-08 15:12 UTC, ivanzuev78 commented on HomeWork_2/test_hw1.py
> +    # Генерирую такой большой массив, потому что надо минимум 10 слов с уникальными символами
> The Russian language is prohibeted.

It was the first and the last time!

2020-11-08 15:13 UTC, ivanzuev78 commented on HomeWork_2/test_hw1.py
> +    text = ["\\u00bbJetzt und hier\\u00ab \\u00bb"]
Sounds good)

2020-11-08 17:11 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +        if len(i) > 1:
String consists of chars.  And each char can be one or more bytes.   But it will always be a single char in Python3.
```
def test_len():
    assert len("Ф") == 1

def test_len2():
    assert len("\u00ab") == 1
```

2020-11-08 17:13 UTC, Cjkjvfnby commented on HomeWork_2/test_hw1.py
> +    os.remove("test_text.txt")
No, it is not about OS.  It is about something else in this method.

2020-11-08 17:15 UTC, Cjkjvfnby requested changes

2020-11-08 17:15 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +    print(symbols)
![image](https://user-images.githubusercontent.com/171597/98471658-f2920e00-21fe-11eb-8cb9-7d889614ef43.png)

If you don't use automated checks, you need to spend more time on self-review.  Code with debug staff should not be submitted for code review.

2020-11-08 17:28 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +    print(symbols)
I still trying to set up automated checks. I'll add checks as soon as possible.

2020-11-08 17:31 UTC, Cjkjvfnby requested changes

2020-11-08 17:31 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +        for letter in word:
So you want to convert a `List[List[str]]` to a `List[str]`.  Can list comperension and other operation to help use in that?   

PS. You have already seen all the required thing so you need to start using them.

2020-11-08 17:46 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +        if len(i) > 1:
Agree, but in "data.txt" all chars are ascii. (at least my PyCharm thinks so) And all non-ascii chars are sequences of ascii chars.
So I have to do something with it. I adapted (def is_ascii) and it can work with both("Ф" and ascii line: "\u00ab") cases.

2020-11-08 17:50 UTC, ivanzuev78 commented on HomeWork_2/test_hw1.py
> +    os.remove("test_text.txt")
In this case I need one more hint.

2020-11-08 18:01 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +        if len(i) > 1:
"\u00ab" is a single char.   It is hard to write some chars so a special techique was invented (escaping),  `\"` is a way to tell a computer that you want to have doublequote in a string. `"\"" == '"'`.   You can treat `\` as a shift key (modifier).   You have one button on a keybord but you can produce different result using modifiers.  So 'n' is single char `n`, but `\n` is line break.

Checking size does not help. 
```
char1 = "\u00ab"
char2 = "«"

print(char1 is char2) 
True
```

2020-11-08 18:02 UTC, Cjkjvfnby commented on HomeWork_2/test_hw1.py
> +    os.remove("test_text.txt")
You have 3 lines of code.  Which of them may fail?

2020-11-08 21:04 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +    return False if len(letter) > 1 or not letter.isascii() else True
Pattern `return False if expression else True` is redundant  use `return not expression`

2020-11-08 21:05 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +    counter = Counter()
It is violates `Complete using only default collections`

2020-11-08 21:06 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +    for i in symbols:
Check Counter constructor.

2020-11-08 21:16 UTC, Cjkjvfnby requested changes

2020-11-08 21:16 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +    skip_unicode_letter = 0
Is this noun represent the variable in a descriptive way?  https://www.oxfordlearnersdictionaries.com/definition/english/skip_2

2020-11-08 21:16 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +                    skip_unicode_letter += 5
What you write in code and what is stored in the string are different.   '\\' in code is just '\' in the memory.  

You need to remove this part.

2020-11-08 21:16 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +                    if letter == "-" and line[index + 1] == "\n":
What is this about?   Do you have a test for that case?

2020-11-08 21:16 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +                        parsed_text.append(tuple(word))
A string is an immutable collection of chars. Do you really need to convert it to the tuple of chars?

2020-11-08 21:16 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +    list_to_return = ["".join(letter for letter in word) for word in text[:10]]
inline

2020-11-08 21:16 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +    for i in symbols:
Use sum and generator expression.

2020-11-08 21:16 UTC, Cjkjvfnby commented on HomeWork_2/test_hw1.py
> +    # Генерирую такой большой массив, потому что надо минимум 10 слов с уникальными символами
> It was the first and the last time!

It is still here.

2020-11-09 04:56 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +    return False if len(letter) > 1 or not letter.isascii() else True
Done

2020-11-10 16:11 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +    counter = Counter()
Done

2020-11-10 16:20 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +    skip_unicode_letter = 0
I'll change it. But its a verb. 
https://www.oxfordlearnersdictionaries.com/definition/english/skip_1

2020-11-10 16:49 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +                    skip_unicode_letter += 5
In this case, I need your help. My PyCharm thinks that "data.txt" consists only of ASCII chars. So I have to parse this chars manually. I don't know how to force PyCharm "see" Unicode chars in this text. I need to do it before removing this part.
'\\' in code is '\' in the memory. (in text one slash is used. example: "gt\u2014dasi")

2020-11-10 16:55 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +                    if letter == "-" and line[index + 1] == "\n":
This is about word wrapping.
I'll do the test.

2020-11-10 18:00 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +    skip_unicode_letter = 0
You should not use the verb for the variable name.   Verbs are fro function and methods.

2020-11-10 18:06 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +                    skip_unicode_letter += 5
> My PyCharm thinks that "data.txt" consists only of ASCII chars.

It is correct. File is pure ascii. 

  `\u2014` is a special language that used inside Python string to tell what should be put to the memory. 
When this is in the text file it is something strange.   As I understand this is a part of task to read that file and convert \u... to unicode chars.    See dialog in chat.

2020-11-10 18:31 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +                        parsed_text.append(tuple(word))
In this realisation "word" is a List[int]. That's all because of problems with encoding.

2020-11-10 18:37 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +    list_to_return = ["".join(letter for letter in word) for word in text[:10]]
Yep

2020-11-10 18:42 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +    for i in symbols:
Magic!

2020-11-11 12:14 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +    skip_unicode_letter = 0
I didn't know. Thanks.

2020-11-11 19:09 UTC, Cjkjvfnby requested changes

2020-11-11 19:09 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +    text_dict = {
How many Unicode chars in the word?  

This list is uncomplete. Filling it manually is a bad idea.  So you need to understand what this numbers means and how to work with them.

2020-11-11 19:09 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +# --------------------- tasks funcs ---------------------------
Please don't use such comments.

2020-11-11 19:09 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +        )[:10]
Can you slice earlie?

2020-11-11 19:09 UTC, Cjkjvfnby commented on HomeWork_2/test_hw1.py
> +    yield None
```suggestion
    yield
```

2020-11-12 04:55 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +                elif letter == "\\":
That is what I am looking for all this time!

2020-11-12 07:02 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +# --------------------- tasks funcs ---------------------------
Ok

2020-11-12 07:05 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +    text_dict = {
I downloaded all Unicode chars and can use them. 
But since you've said about "unicode-escape" this is not actual.

2020-11-12 07:12 UTC, ivanzuev78 commented on HomeWork_2/hw1.py
> +        )[:10]
This is not obvious to me. 
I slice exact "sorted(data)[:10]". 
If I slice before "sort", I'll get the wrong data.

2020-11-12 07:14 UTC, ivanzuev78 commented on HomeWork_2/test_hw1.py
> +    yield None
Didn't know it is possible.

2020-11-12 17:29 UTC, Cjkjvfnby commented on HomeWork_2/hw1.py
> +        )[:10]
```python
[foo(x) for x in sorted(...)[:10]]
[foo(x) for x in sorted(...)][:10]
```

2020-11-12 17:30 UTC, Cjkjvfnby approved these changes

2020-11-13 03:21 UTC, merged